config/routes.rb
BestBeach::Application.routes.draw do

  root :to => 'beaches#index'
  resources :beaches, only: [:index, :show, :create]

end

app/models/beach.rb
class Beach < ActiveRecord::Base
  validates :name, :presence => true
  validates :yelp_id, :uniqueness => true
end

app/models/information.rb
class Information
  attr_accessor :get_beach_list, :insert_beaches_into_db, :get_beach, :response1, :response2
  
  def initialize
    @client = Yelp::Client.new
    @response1 = []
    @response2 = {}
  end
  
  def get_beach_list(lat, long)
    return unless lat.presence && long.presence

    request = Yelp::V2::Search::Request::GeoPoint.new(
              :latitude => lat,
              :longitude => long,
              :category_filter => ['beaches'],
              :limit => 9,
              :radius_filter => 40000,
              :sort => 0)
    @response = @client.search(request)['businesses']
    insert_beaches_into_db
  end

  def insert_beaches_into_db
    @response.each do |beach|
      if Beach.find_by_yelp_id("#{beach}").nil?
        Beach.create(name: "#{beach['name']}", yelp_id: "#{beach['id']}")
      end
    end
  
  end

  def get_beach(yelp_id)
    request = Yelp::V2::Business::Request::Id.new(
      :yelp_business_id => yelp_id)
    @response = @client.search(request)
  end
end

app/models/weather.rb
class Weather
  attr_accessor :client

  def initialize
    @client = Wunderground.new(ENV["WUNDERGROUND_TOKEN"])
  end

end

app/models/yelp.rb
class Yelp
  attr_accessible :get_beaches, :insert_beaches_into_db, :response
  
  def initialize
    @client = Yelp::Client.new
    @response = []
  end
  
  def get_beaches(lat, long)
    request = Yelp::V2::Search::Request::GeoPoint.new(
              :latitude => lat,
              :longitude => long,
              :category_filter => ['beaches'],
              :radius_filter => 40000,
              :sort => 2)
    @response = client.search(request)['businesses']
  end

  def insert_beaches_into_db
    @response.each do |beach|
      if Beach.find_by_yelp_id(beach).nil?
        Beach.create(name: beach['name'], yelp_id: beach['id'])
      end
  
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include BeachesHelper

end

app/controllers/beaches_controller.rb
class BeachesController < ApplicationController

  def index

  end

  def create
    latitude = params[:latitude]
    longitude = params[:longitude]

    cookies.encrypted[:coordinates] = JSON.generate([latitude, longitude])

    yelp_call = Information.new
    @response = yelp_call.get_beach_list(latitude, longitude)

    @origin = origin_set
  end

  def show
    @beach = Beach.find_by_yelp_id(params[:id])

    yelp_call = Information.new
    @yelp_response = yelp_call.get_beach(@beach.yelp_id)
    @zip = @yelp_response['location']['postal_code']

    origin = origin_set

    destination = get_destination(@yelp_response['location']['address'][0], @zip)

    #@drive_time = mapquest_api(origin, destination)
    @drive_time = nil

    @directions = "https://maps.google.com/maps?saddr=#{origin}&daddr=#{destination}"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beaches_helper.rb
module BeachesHelper

  def origin_set
    JSON.parse(cookies.encrypted[:coordinates]).join(",")
  end

  def weather(postal_code)
    w = Wunderground.new(ENV["WUNDERGROUND_TOKEN"])
    sleep(0.5)
    @weather = w.forecast_and_conditions_and_astronomy_for(postal_code)
    return @weather
  end
  
  # Need to refactor this
  def get_destination(address, zip)
    destination = []
    if address && zip
      unless address.empty?
        destination << address.split(" ")
        destination << zip
        destination = destination.flatten.join(",")
        if destination.include? "&"
          return destination.gsub!("&", "and")
        else
          return destination
        end
      end
    elsif zip
      destination << zip
      destination = destination.flatten.join
      if destination.include? "&"
        return destination.gsub!("&", "and")
      else
        return destination
      end
    end
  end

  def mapquest_api(origin, dest)
    directions = Typhoeus.get(
      "http://www.mapquestapi.com/directions/v2/route?key=Fmjtd%7Cluubnu0all%2C7n%3Do5-9u1s0z&from=#{origin}&to=#{dest}"
      )

    @results = JSON.parse(directions.body)
    return @results
  end

  def photos_link(location, city)
    link = "http://www.flickr.com/search/?q=#{location + " " + city}&ss=1&ct=0&mt=all&w=all&adv=1"
    return link
  end
end

app/views/beaches/_beach_summary.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 text-center well beach">
  <img src="<%= x['image_url'] %>" class="img-circle">

  <h2><%= link_to x['name'], beach_path(x['id']) %></h2>

  <p><img src="<%= x['rating_img_url'] %>"> <%= x['review_count']%> <a href="http://www.yelp.com"><img src="/assets/miniMapLogo.png"></a> reviews
  </p>

  <!--
  <%# @destination = get_destination(x['location']['address'][0], x['location']['postal_code']) %>

  <%# if !@destination.nil? && !@destination.empty? %>
    <%# @results = mapquest_api(@origin, @destination) %>

    <%# unless @results['route'].nil? %>
      <p class="drive_time"><%#= @results['route']['realTime']/60 %> minutes away</p>
    <%# end %>

  <%# end %>
  -->

  <% if x['location']['postal_code'] %>
    <% cache(x['location']['postal_code'], :expires_in => 15.minutes) do %>
      <% @weather = weather(x['location']['postal_code']) %>
      <p>
        <img src="<%= @weather['current_observation']['icon_url'] %>">
      <%= @weather['current_observation']['weather'] %>, <%= @weather['current_observation']['temperature_string'] %>
      </p>
    <% end %>
  <% end %>

</div>

app/views/beaches/_yelp_reviews.html.erb
<div class="col-md-7 pull-left">
  <% @yelp_response['reviews'].each do |review| %>
    <p><img src="<%= review['rating_image_url']%>"> <%= Time.at(review['time_created']).to_date %><br>
      <%= review['excerpt'] %> <a href="<%= @yelp_response['url'] %>#hrid:<%= review['id']%>" target="_blank">Read more</a><br>
    </p>
  <% end %>
  <p class="pull-right"><a href="http://www.yelp.com"><img src="/assets/reviewsFromYelpWHT.gif"></a></p>

</div>

app/views/beaches/create.html.erb
<% unless cookies.encrypted[:coordinates] %>
  <script>
    getGeoLocation();
  </script>
<% end %>

<div class="page-header">
  <div class="container">
    <h1>Top Beaches</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if !@response.empty? %>
      <% @response.each do |x| %>

        <%= render "beach_summary", :x => x %>
      
      <% end %>
    <% else %>
      <div class="col-xs-12">
        <p>Sorry, but there are no beaches near your location.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/beaches/index.html.erb
<script>
  getGeoLocation();
</script>

<div id="hero">
  <div id="main-intro">
    <div class="container">
      <h1>Welcome!</h1>
      <p class="lead">In the mood to go to the beach today but not sure where to go? Let us help you.</p>
      <%= form_tag("/beaches", method: "post", class: "form-inline") do %>
        <div class="form-group">
          <label class="sr-only" for="lat">Latitude</label>
          <input type="string" name="latitude" id="lat" class="form-control" placeholder="latitude">
        </div>
        <div class="form-group">
          <label class="sr-only" for="long">Longitude</label>
          <input type="string" name="longitude" id="long" class="form-control" placeholder="longitude">
        </div>
        <button type="submit" class="btn btn-default">Go</button>
      <% end %>
    </div>

  </div>
</div>

app/views/beaches/show.html.erb
<% unless cookies[:coordinates] %>
  <script>
    getGeoLocation();
  </script>
<% end %>

<div class="page-header">
  <div class="container">
      <h1><%= @beach.name %> <small><a href="<%= @yelp_response['url'] %>" target="_blank"><img src="<%= @yelp_response['rating_img_url'] %>"></a> <%= @yelp_response['review_count'] %> reviews</small></h1>
  </div>
</div>

<div class="container">

  <div class="row">
    <img src="<%= @beach.main_image %>">
    <div class="col-sm-4 col-md-4 col-md-offset-1 well pull-right">
      <address>
        <%= @yelp_response['location']['address'][0] %><br>
          <% if @yelp_response['location']['cross_streets'] %>
            Cross streets: <%= @yelp_response['location']['cross_streets'] %><br>
          <% end %>
        <%= @yelp_response['location']['city'] %>, <%= @yelp_response['location']['state_code'] %> <%= @zip %><br>
        <a href="<%= @directions %>">Directions</a>
      </address>

      <% if @drive_time && @drive_time['route'].present? %>
        <p>
          <strong>Distance:</strong> <%= @drive_time['route']['distance'] %> miles<br>
          <strong>Regular Travel Time:</strong> 
          <%= @drive_time['route']['time']/60 %> minutes<br>
          <strong>Current Travel time:</strong> 
          <%= @drive_time['route']['realTime']/60 %> minutes
        </p>
      <% end %>
      <p><a href="<%= photos_link(@beach.name, @yelp_response['location']['city']) %>">See photos on Flickr</a></p>
    </div>

    <%= render "yelp_reviews" %>

  </div>

<% cache(@yelp_response['id'], :expires_in => 5.minutes) do %>
  <% @weather = weather(@zip) %>
  <div class="row">
    <h2>Weather Information</h2>
    <% if @weather['current_observation'] %>
    <div class="col-md-6">

      <div class="row">
        <div class="col-md-2 pull-left">
          <p class="current_temp"><img src="<%= @weather['current_observation']['icon_url'] %>">
          </p>
        </div>
        <div class="col-md-10 pull-right">
          <p><span class="current_temp"><%= @weather['current_observation']['temperature_string'] %></span><br>
            <%= @weather['current_observation']['weather'] %>
          </p>
        </div>
      </div>
      <p><strong><%= @weather['forecast']['txt_forecast']['forecastday'][0]['title'] %>:</strong> <%= @weather['forecast']['txt_forecast']['forecastday'][0]['fcttext'] %></p>
      <p><strong><%= @weather['forecast']['txt_forecast']['forecastday'][1]['title'] %>:</strong> <%= @weather['forecast']['txt_forecast']['forecastday'][1]['fcttext'] %></p>

      <p>
        <a href="<%= @weather['current_observation']['forecast_url'] %>" target="_blank">Full Forecast</a>
      </p>
    </div>
    
    <div class="col-md-6 table-responsive">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Feels like:</td>
            <td><%= @weather['current_observation']['feelslike_string'] %></td>
          <tr>
            <td>Humidity:</td>
            <td><%= @weather['current_observation']['relative_humidity'] %></td>
          </tr>
          <tr>
            <td>Wind:</td>
            <td><%= @weather['current_observation']['wind_string'] %></td>
          </tr>
          <tr>
            <td>UV Index:</td>
            <td><%= @weather['current_observation']['UV'] %> out of 16</td>
          </tr>
          <tr>
            <td>Sunset:</td>
            <td><%= @weather['sun_phase']['sunset']['hour'] %>:<%= @weather['sun_phase']['sunset']['minute'] %></td>
          </tr>
        </tbody>
      </table>
      <p>
        <strong>Observed location:</strong> <%= @weather['current_observation']['observation_location']['city'] %><br>
        <em><%= @weather['current_observation']['observation_time'] %></em>
      </p>
    </div>
    <% else %>
      <p>Sorry there is no weather information for this location currently available.</p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <p>Made by <a href="http://amy-mac.com">Amy MacKinnon</a>, 2013</p>
      </div>
      <div class="col-md-6">
        <p>
        <a href="http://www.wunderground.com"><img class="img-responsive pull-right" src="/assets/wundergroundLogo_white_horz.png" alt="Weather Undergroud logo"></a>
      </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="/" class="navbar-brand">BestBeachNow</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <form class="navbar-form navbar-right hidden" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BestBeachNow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">

    <%= render "/layouts/nav" %>

    <%= yield %>

  </div>
  
  <%= render "/layouts/footer" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45162642-1', 'bestbeachtoday.herokuapp.com');
  ga('send', 'pageview');

</script>
</body>
</html>